### ISSUE TITLE
求解  可以教一下部署嘛。必须要用yarn嘛

### ISSUE THREAD

**Issue by zym0101** [calebman/girlfriend-gift-collection#2]

**Comment by calebman** [comment]
部署其实就是两步：
1. 编译打包得到静态页面文件
2. 将静态页面文件放置到 web 服务器中，这个 web 服务器可以是 Tomcat、Nginx、甚至是 GithubPages

## 先说第一步

- [birth-want-to-say](https://github.com/calebman/girlfriend-gift-collection/tree/master/birth-want-to-say) 这个项目由于本身就是静态页面文件了，所以直接将源代码放到 web 服务器即可
- [chat-want-to-say](https://github.com/calebman/girlfriend-gift-collection/tree/master/chat-want-to-say) 这个项目由于使用了 vite 构建，需要经过一层编译才能得到静态页面文件，可以参考 https://cn.vitejs.dev/guide/ 获得 vite 相关帮助，届时你也能够了解项目的目录结构代表什么

## 再说第二步

- 在你得到静态页面文件后，如果你有私人的云服务器资源，可以考虑安装 web 服务，然后将页面放上去即可。
- 如果没有私人的云服务器，可以考虑托管到 GithubPages、GiteePages 来展示，相关教程可以自己搜索下
